<?php

namespace Database\Seeders;

use App\Models\JenisSurat;
use Illuminate\Database\Seeder;

class JenisSuratSeeder extends Seeder
{
    public function run(): void
    {
        $data = [

            // ── PERNIKAHAN ────────────────────────────────────────────────────
            [
                'kode'                  => 'NIKAH_P',
                'nama'                  => 'Pengantar Perkawinan (Perempuan)',
                'kategori'              => 'Pernikahan',
                'nomor_format'          => '474.2',
                'melibatkan_pihak_luar' => true,
                'template_blade'        => 'surat.nikah_p',
                'urutan'                => 1,
                'fields_tambahan'       => [
                    ['key' => 'nama_calon_suami',   'label' => 'Nama Calon Suami',     'type' => 'text', 'required' => true],
                    ['key' => 'nik_calon_suami',    'label' => 'NIK Calon Suami',      'type' => 'text', 'required' => false],
                    ['key' => 'tempat_lahir_suami', 'label' => 'Tempat Lahir Suami',   'type' => 'text', 'required' => false],
                    ['key' => 'tgl_lahir_suami',    'label' => 'Tgl Lahir Suami',      'type' => 'date', 'required' => false],
                    ['key' => 'pekerjaan_suami',    'label' => 'Pekerjaan Suami',      'type' => 'text', 'required' => false],
                    ['key' => 'alamat_suami',       'label' => 'Alamat Suami',         'type' => 'text', 'required' => false],
                    ['key' => 'tanggal_akad',       'label' => 'Rencana Tanggal Akad', 'type' => 'date', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'NIKAH_L',
                'nama'                  => 'Pengantar Perkawinan (Laki-laki)',
                'kategori'              => 'Pernikahan',
                'nomor_format'          => '474.2',
                'melibatkan_pihak_luar' => true,
                'template_blade'        => 'surat.nikah_l',
                'urutan'                => 2,
                'fields_tambahan'       => [
                    ['key' => 'nama_calon_istri',   'label' => 'Nama Calon Istri',     'type' => 'text', 'required' => true],
                    ['key' => 'nik_calon_istri',    'label' => 'NIK Calon Istri',      'type' => 'text', 'required' => false],
                    ['key' => 'tempat_lahir_istri', 'label' => 'Tempat Lahir Istri',   'type' => 'text', 'required' => false],
                    ['key' => 'tgl_lahir_istri',    'label' => 'Tgl Lahir Istri',      'type' => 'date', 'required' => false],
                    ['key' => 'pekerjaan_istri',    'label' => 'Pekerjaan Istri',      'type' => 'text', 'required' => false],
                    ['key' => 'alamat_istri',       'label' => 'Alamat Istri',         'type' => 'text', 'required' => false],
                    ['key' => 'tanggal_akad',       'label' => 'Rencana Tanggal Akad', 'type' => 'date', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'KETERANGAN_WALI',
                'nama'                  => 'Surat Keterangan Wali',
                'kategori'              => 'Pernikahan',
                'nomor_format'          => '474.2',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.keterangan_wali',
                'urutan'                => 3,
                'fields_tambahan'       => [
                    ['key' => 'nama_wali',        'label' => 'Nama Wali',            'type' => 'text', 'required' => true],
                    ['key' => 'hubungan_wali',    'label' => 'Hubungan dengan Wali', 'type' => 'text', 'required' => true],
                    ['key' => 'nama_calon_istri', 'label' => 'Nama Calon Istri',     'type' => 'text', 'required' => true],
                ],
            ],
            [
                'kode'                  => 'PERNYATAAN_JEJAKA',
                'nama'                  => 'Surat Pernyataan Jejaka',
                'kategori'              => 'Pernikahan',
                'nomor_format'          => '474.2',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pernyataan_jejaka',
                'urutan'                => 4,
                'fields_tambahan'       => [],
            ],
            [
                'kode'                  => 'DISPENSASI_NIKAH',
                'nama'                  => 'Surat Dispensasi Nikah',
                'kategori'              => 'Pernikahan',
                'nomor_format'          => '474.2',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.dispensasi_nikah',
                'urutan'                => 5,
                'fields_tambahan'       => [
                    ['key' => 'alasan_dispensasi', 'label' => 'Alasan Dispensasi', 'type' => 'textarea', 'required' => true],
                ],
            ],
            [
                'kode'                  => 'DUPLIKAT_NIKAH',
                'nama'                  => 'Surat Pengantar Duplikat Nikah',
                'kategori'              => 'Pernikahan',
                'nomor_format'          => '474.2',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.duplikat_nikah',
                'urutan'                => 6,
                'fields_tambahan'       => [
                    ['key' => 'nama_pasangan', 'label' => 'Nama Pasangan', 'type' => 'text', 'required' => true],
                    ['key' => 'tahun_menikah', 'label' => 'Tahun Menikah', 'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'BELUM_MENIKAH',
                'nama'                  => 'Surat Keterangan Belum Pernah Menikah',
                'kategori'              => 'Pernikahan',
                'nomor_format'          => '474.2',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.belum_menikah',
                'urutan'                => 7,
                'fields_tambahan'       => [],
            ],

            // ── KEPENDUDUKAN ──────────────────────────────────────────────────
            [
                'kode'                  => 'DOMISILI',
                'nama'                  => 'Surat Keterangan Domisili',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.domisili',
                'urutan'                => 8,
                'fields_tambahan'       => [
                    ['key' => 'keperluan', 'label' => 'Keperluan', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'kode'                  => 'DOMISILI_MASJID',
                'nama'                  => 'Surat Keterangan Domisili Masjid',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.domisili_masjid',
                'urutan'                => 9,
                'fields_tambahan'       => [
                    ['key' => 'nama_masjid',   'label' => 'Nama Masjid/Mushola', 'type' => 'text', 'required' => true],
                    ['key' => 'alamat_masjid', 'label' => 'Alamat Masjid',       'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'BIODATA',
                'nama'                  => 'Surat Keterangan Biodata Penduduk',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.biodata',
                'urutan'                => 10,
                'fields_tambahan'       => [
                    ['key' => 'keperluan', 'label' => 'Keperluan', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'kode'                  => 'PENGANTAR_KTP',
                'nama'                  => 'Surat Pengantar Pembuatan KTP',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pengantar_ktp',
                'urutan'                => 11,
                'fields_tambahan'       => [
                    ['key' => 'jenis_permohonan', 'label' => 'Jenis Permohonan', 'type' => 'select',
                     'required' => true, 'options' => ['Baru', 'Perpanjangan', 'Hilang', 'Rusak']],
                ],
            ],
            [
                'kode'                  => 'PENGANTAR_KK',
                'nama'                  => 'Surat Pengantar Pembuatan KK',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pengantar_kk',
                'urutan'                => 12,
                'fields_tambahan'       => [
                    ['key' => 'jenis_permohonan', 'label' => 'Jenis Permohonan', 'type' => 'select',
                     'required' => true, 'options' => ['Baru', 'Perubahan Data', 'Hilang']],
                ],
            ],
            [
                'kode'                  => 'PENGANTAR_KIA',
                'nama'                  => 'Surat Pengantar Pembuatan KIA',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pengantar_kia',
                'urutan'                => 13,
                'fields_tambahan'       => [],
            ],
            [
                'kode'                  => 'PINDAH_KELUAR',
                'nama'                  => 'Surat Pengantar Pindah Penduduk (Keluar)',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pindah_keluar',
                'urutan'                => 14,
                'fields_tambahan'       => [
                    ['key' => 'alamat_tujuan', 'label' => 'Alamat Tujuan Pindah', 'type' => 'text', 'required' => true],
                    ['key' => 'alasan_pindah', 'label' => 'Alasan Pindah',        'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'PINDAH_MASUK',
                'nama'                  => 'Surat Keterangan Masuk Penduduk',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pindah_masuk',
                'urutan'                => 15,
                'fields_tambahan'       => [
                    ['key' => 'alamat_asal',   'label' => 'Alamat Asal',   'type' => 'text', 'required' => true],
                    ['key' => 'tanggal_masuk', 'label' => 'Tanggal Masuk', 'type' => 'date', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'PERNYATAAN_PINDAH',
                'nama'                  => 'Surat Pernyataan Pindah',
                'kategori'              => 'Kependudukan',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pernyataan_pindah',
                'urutan'                => 16,
                'fields_tambahan'       => [
                    ['key' => 'alamat_tujuan', 'label' => 'Alamat Tujuan', 'type' => 'text', 'required' => true],
                ],
            ],

            // ── KELAHIRAN & KEMATIAN ──────────────────────────────────────────
            [
                'kode'                  => 'KELAHIRAN_BARU',
                'nama'                  => 'Surat Keterangan Kelahiran (Baru)',
                'kategori'              => 'Kelahiran & Kematian',
                'nomor_format'          => '474.1',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.kelahiran_baru',
                'urutan'                => 17,
                'fields_tambahan'       => [
                    ['key' => 'nama_bayi',          'label' => 'Nama Bayi',          'type' => 'text',   'required' => true],
                    ['key' => 'jenis_kelamin_bayi', 'label' => 'Jenis Kelamin Bayi', 'type' => 'select', 'required' => true,
                     'options' => ['Laki-laki', 'Perempuan']],
                    ['key' => 'tanggal_lahir_bayi', 'label' => 'Tanggal Lahir Bayi', 'type' => 'date',   'required' => true],
                    ['key' => 'tempat_lahir_bayi',  'label' => 'Tempat Lahir Bayi',  'type' => 'text',   'required' => true],
                    ['key' => 'nama_ayah',          'label' => 'Nama Ayah',          'type' => 'text',   'required' => true],
                    ['key' => 'nama_ibu',           'label' => 'Nama Ibu',           'type' => 'text',   'required' => true],
                ],
            ],
            [
                'kode'                  => 'KELAHIRAN_LAMA',
                'nama'                  => 'Surat Keterangan Kelahiran (Terlambat/Lama)',
                'kategori'              => 'Kelahiran & Kematian',
                'nomor_format'          => '474.1',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.kelahiran_lama',
                'urutan'                => 18,
                'fields_tambahan'       => [
                    ['key' => 'nama_bayi',          'label' => 'Nama',                    'type' => 'text',     'required' => true],
                    ['key' => 'jenis_kelamin_bayi', 'label' => 'Jenis Kelamin',           'type' => 'select',   'required' => true,
                     'options' => ['Laki-laki', 'Perempuan']],
                    ['key' => 'tanggal_lahir_bayi', 'label' => 'Tanggal Lahir',           'type' => 'date',     'required' => true],
                    ['key' => 'tempat_lahir_bayi',  'label' => 'Tempat Lahir',            'type' => 'text',     'required' => true],
                    ['key' => 'nama_ayah',          'label' => 'Nama Ayah',               'type' => 'text',     'required' => true],
                    ['key' => 'nama_ibu',           'label' => 'Nama Ibu',                'type' => 'text',     'required' => true],
                    ['key' => 'keterangan_lama',    'label' => 'Keterangan Keterlambatan','type' => 'textarea', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'KEMATIAN_BARU',
                'nama'                  => 'Surat Keterangan Kematian (Baru)',
                'kategori'              => 'Kelahiran & Kematian',
                'nomor_format'          => '474.3',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.kematian_baru',
                'urutan'                => 19,
                'fields_tambahan'       => [
                    ['key' => 'tanggal_meninggal', 'label' => 'Tanggal Meninggal', 'type' => 'date', 'required' => true],
                    ['key' => 'tempat_meninggal',  'label' => 'Tempat Meninggal',  'type' => 'text', 'required' => false],
                    ['key' => 'sebab_meninggal',   'label' => 'Sebab Meninggal',   'type' => 'text', 'required' => false],
                    ['key' => 'nama_pelapor',      'label' => 'Nama Pelapor',      'type' => 'text', 'required' => false],
                    ['key' => 'hubungan_pelapor',  'label' => 'Hubungan Pelapor',  'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'KEMATIAN_LAMA',
                'nama'                  => 'Surat Keterangan Kematian (Lama/Terlambat)',
                'kategori'              => 'Kelahiran & Kematian',
                'nomor_format'          => '474.3',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.kematian_lama',
                'urutan'                => 20,
                'fields_tambahan'       => [
                    ['key' => 'tanggal_meninggal', 'label' => 'Tanggal Meninggal',        'type' => 'date',     'required' => true],
                    ['key' => 'tempat_meninggal',  'label' => 'Tempat Meninggal',         'type' => 'text',     'required' => false],
                    ['key' => 'sebab_meninggal',   'label' => 'Sebab Meninggal',          'type' => 'text',     'required' => false],
                    ['key' => 'keterangan_lama',   'label' => 'Keterangan Keterlambatan', 'type' => 'textarea', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'PERNYATAAN_KEMATIAN',
                'nama'                  => 'Surat Pernyataan Kematian',
                'kategori'              => 'Kelahiran & Kematian',
                'nomor_format'          => '474.3',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pernyataan_kematian',
                'urutan'                => 21,
                'fields_tambahan'       => [
                    ['key' => 'tanggal_meninggal', 'label' => 'Tanggal Meninggal', 'type' => 'date', 'required' => true],
                    ['key' => 'nama_saksi_1',      'label' => 'Nama Saksi 1',      'type' => 'text', 'required' => false],
                    ['key' => 'nama_saksi_2',      'label' => 'Nama Saksi 2',      'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'PENGANTAR_AKTA_LAHIR',
                'nama'                  => 'Surat Pengantar Akta Kelahiran',
                'kategori'              => 'Kelahiran & Kematian',
                'nomor_format'          => '474.1',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pengantar_akta_lahir',
                'urutan'                => 22,
                'fields_tambahan'       => [
                    ['key' => 'nama_bayi',          'label' => 'Nama Anak',      'type' => 'text', 'required' => true],
                    ['key' => 'tanggal_lahir_bayi', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true],
                ],
            ],

            // ── EKONOMI & SOSIAL ──────────────────────────────────────────────
            [
                'kode'                  => 'USAHA',
                'nama'                  => 'Surat Keterangan Usaha',
                'kategori'              => 'Ekonomi & Sosial',
                'nomor_format'          => '503',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.usaha',
                'urutan'                => 23,
                'fields_tambahan'       => [
                    ['key' => 'nama_usaha',   'label' => 'Nama Usaha',   'type' => 'text', 'required' => true],
                    ['key' => 'jenis_usaha',  'label' => 'Jenis Usaha',  'type' => 'text', 'required' => true],
                    ['key' => 'alamat_usaha', 'label' => 'Alamat Usaha', 'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'USAHA_BRI',
                'nama'                  => 'Surat Keterangan Usaha (BRI)',
                'kategori'              => 'Ekonomi & Sosial',
                'nomor_format'          => '503',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.usaha_bri',
                'urutan'                => 24,
                'fields_tambahan'       => [
                    ['key' => 'nama_usaha',       'label' => 'Nama Usaha',          'type' => 'text', 'required' => true],
                    ['key' => 'jenis_usaha',      'label' => 'Jenis Usaha',         'type' => 'text', 'required' => true],
                    ['key' => 'alamat_usaha',     'label' => 'Alamat Usaha',        'type' => 'text', 'required' => false],
                    ['key' => 'nomor_rekening',   'label' => 'Nomor Rekening BRI',  'type' => 'text', 'required' => false],
                    ['key' => 'keperluan_kredit', 'label' => 'Keperluan Kredit',    'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'PENGHASILAN',
                'nama'                  => 'Surat Keterangan Penghasilan',
                'kategori'              => 'Ekonomi & Sosial',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.penghasilan',
                'urutan'                => 25,
                'fields_tambahan'       => [
                    ['key' => 'penghasilan_perbulan', 'label' => 'Penghasilan/Bulan (Rp)', 'type' => 'number', 'required' => true],
                    ['key' => 'keperluan',            'label' => 'Keperluan',              'type' => 'text',   'required' => true],
                ],
            ],
            [
                'kode'                  => 'TIDAK_MAMPU',
                'nama'                  => 'Surat Keterangan Tidak Mampu',
                'kategori'              => 'Ekonomi & Sosial',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.tidak_mampu',
                'urutan'                => 26,
                'fields_tambahan'       => [
                    ['key' => 'keperluan', 'label' => 'Keperluan', 'type' => 'text', 'required' => true],
                ],
            ],
            [
                'kode'                  => 'TIDAK_MAMPU_DOMISILI',
                'nama'                  => 'Surat Keterangan Tidak Mampu (Domisili)',
                'kategori'              => 'Ekonomi & Sosial',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.tidak_mampu_domisili',
                'urutan'                => 27,
                'fields_tambahan'       => [
                    ['key' => 'keperluan',       'label' => 'Keperluan',       'type' => 'text', 'required' => true],
                    ['key' => 'tujuan_instansi', 'label' => 'Tujuan Instansi', 'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'TIDAK_MAMPU_TPA',
                'nama'                  => 'Surat Keterangan Tidak Mampu (TPA)',
                'kategori'              => 'Ekonomi & Sosial',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.tidak_mampu_tpa',
                'urutan'                => 28,
                'fields_tambahan'       => [
                    ['key' => 'nama_tpa', 'label' => 'Nama TPA', 'type' => 'text', 'required' => true],
                ],
            ],

            // ── KETERANGAN LAIN ───────────────────────────────────────────────
            [
                'kode'                  => 'KEHILANGAN',
                'nama'                  => 'Surat Keterangan Kehilangan',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '145',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.kehilangan',
                'urutan'                => 29,
                'fields_tambahan'       => [
                    ['key' => 'barang_hilang',    'label' => 'Barang/Dokumen yang Hilang', 'type' => 'text',     'required' => true],
                    ['key' => 'keterangan_hilang','label' => 'Keterangan Kehilangan',      'type' => 'textarea', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'HARGA_TANAH',
                'nama'                  => 'Surat Keterangan Harga Tanah',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '595.1',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.harga_tanah',
                'urutan'                => 30,
                'fields_tambahan'       => [
                    ['key' => 'luas_tanah',   'label' => 'Luas Tanah (m²)',  'type' => 'number', 'required' => true],
                    ['key' => 'lokasi_tanah', 'label' => 'Lokasi Tanah',     'type' => 'text',   'required' => true],
                    ['key' => 'harga_per_m2', 'label' => 'Harga per m² (Rp)','type' => 'number', 'required' => true],
                    ['key' => 'peruntukan',   'label' => 'Peruntukan',       'type' => 'text',   'required' => false],
                ],
            ],
            [
                'kode'                  => 'TANAH_BSPS',
                'nama'                  => 'Surat Keterangan Tanah BSPS',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '595.1',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.tanah_bsps',
                'urutan'                => 31,
                'fields_tambahan'       => [
                    ['key' => 'luas_tanah',    'label' => 'Luas Tanah (m²)',   'type' => 'number', 'required' => true],
                    ['key' => 'lokasi_tanah',  'label' => 'Lokasi Tanah',      'type' => 'text',   'required' => true],
                    ['key' => 'nomor_peserta', 'label' => 'Nomor Peserta BSPS','type' => 'text',   'required' => false],
                ],
            ],
            [
                'kode'                  => 'BEDA_IDENTITAS',
                'nama'                  => 'Surat Keterangan Beda Nama/Alamat/Tanggal Lahir',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.beda_identitas',
                'urutan'                => 32,
                'fields_tambahan'       => [
                    ['key' => 'jenis_beda',      'label' => 'Jenis Perbedaan',      'type' => 'select', 'required' => true,
                     'options' => ['Nama', 'Alamat', 'Tanggal Lahir', 'Kombinasi']],
                    ['key' => 'data_di_dokumen', 'label' => 'Data di Dokumen Lama', 'type' => 'text',   'required' => true],
                    ['key' => 'data_yang_benar', 'label' => 'Data yang Benar',      'type' => 'text',   'required' => true],
                    ['key' => 'nama_dokumen',    'label' => 'Nama Dokumen',         'type' => 'text',   'required' => false],
                ],
            ],
            [
                'kode'                  => 'SKCK',
                'nama'                  => 'Surat Pengantar SKCK',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.skck',
                'urutan'                => 33,
                'fields_tambahan'       => [
                    ['key' => 'keperluan',       'label' => 'Keperluan SKCK',  'type' => 'text', 'required' => true],
                    ['key' => 'tujuan_instansi', 'label' => 'Tujuan Instansi', 'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'IJIN_KERAMAIAN',
                'nama'                  => 'Surat Ijin Keramaian',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '300',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.ijin_keramaian',
                'urutan'                => 34,
                'fields_tambahan'       => [
                    ['key' => 'nama_acara',        'label' => 'Nama Acara',         'type' => 'text',   'required' => true],
                    ['key' => 'tanggal_acara',     'label' => 'Tanggal Acara',      'type' => 'date',   'required' => true],
                    ['key' => 'tempat_acara',      'label' => 'Tempat Acara',       'type' => 'text',   'required' => true],
                    ['key' => 'perkiraan_peserta', 'label' => 'Perkiraan Peserta',  'type' => 'number', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'PENGANTAR_PERJALANAN',
                'nama'                  => 'Surat Pengantar Perjalanan',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pengantar_perjalanan',
                'urutan'                => 35,
                'fields_tambahan'       => [
                    ['key' => 'tujuan_perjalanan', 'label' => 'Tujuan Perjalanan', 'type' => 'text', 'required' => true],
                    ['key' => 'keperluan',         'label' => 'Keperluan',         'type' => 'text', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'PENGANTAR_CERAI',
                'nama'                  => 'Surat Pengantar Cerai',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '474.2',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pengantar_cerai',
                'urutan'                => 36,
                'fields_tambahan'       => [
                    ['key' => 'nama_pasangan', 'label' => 'Nama Pasangan', 'type' => 'text',     'required' => true],
                    ['key' => 'alasan_cerai',  'label' => 'Alasan Cerai',  'type' => 'textarea', 'required' => false],
                ],
            ],
            [
                'kode'                  => 'PENGANTAR_DUPLIKAT',
                'nama'                  => 'Surat Pengantar Duplikat Dokumen',
                'kategori'              => 'Keterangan Lain',
                'nomor_format'          => '474.4',
                'melibatkan_pihak_luar' => false,
                'template_blade'        => 'surat.pengantar_duplikat',
                'urutan'                => 37,
                'fields_tambahan'       => [
                    ['key' => 'nama_dokumen',   'label' => 'Nama Dokumen',    'type' => 'text', 'required' => true],
                    ['key' => 'alasan_duplikat','label' => 'Alasan Duplikat', 'type' => 'text', 'required' => false],
                ],
            ],
        ];

        foreach ($data as $item) {
            $fields = $item['fields_tambahan'];
            unset($item['fields_tambahan']);

            JenisSurat::updateOrCreate(
                ['kode' => $item['kode']],
                array_merge($item, ['fields_tambahan' => $fields])
            );
        }
    }
}